#!/bin/bash
# Toolchain Environment Setup for Anvil OS
# Generated by Architect (Manual Intervention)

# Resolve absolute path to the toolchain root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLCHAIN_BIN="${SCRIPT_DIR}/bin"

# Export Path
export PATH="${TOOLCHAIN_BIN}:${PATH}"

# Export Standard Cross-Compile Variables
export CROSS_COMPILE="x86_64-unknown-linux-musl-"
export ARCH="x86_64"

# Export CC/CXX explicitly to ensure build systems pick them up
export CC="${CROSS_COMPILE}gcc"
export CXX="${CROSS_COMPILE}g++"
export AR="${CROSS_COMPILE}ar"
export NM="${CROSS_COMPILE}nm"
export LD="${CROSS_COMPILE}ld"
export STRIP="${CROSS_COMPILE}strip"
export RANLIB="${CROSS_COMPILE}ranlib"

echo "Anvil Toolchain Activated: ${CROSS_COMPILE}"
